### ISSUE TITLE
remove the sourcemap url

### ISSUE THREAD

**Issue by tjx666** [eslint/eslint-visitor-keys#43]
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/41773861/226165763-dfad3029-b14e-475b-abfb-80fe8b70f8d9.png">

version: eslint-visitor-keys@3.3.0

**Comment by Rec0iL99** [comment]
Hi @tjx666, thanks for the issue. The `sourceMappingURL` comment is autogenerated by rollup and helps navigate to the source map file and finally to the original source code during debugging. I believe this comment is generated by rollup because of `sourcemap: true` in [`rollup.config.js`](https://github.com/eslint/eslint-visitor-keys/blob/0398109f1f751c58be3bd3206d22ae9c1b269219/rollup.config.js#L7).

**Comment by tjx666** [comment]
You should set `sourcemap: false` when build for production, or it will cause debugger tools issue because you decale the sourceMappingURL but not actually exists;

<img width="1440" alt="image" src="https://user-images.githubusercontent.com/41773861/226199909-09f8f56a-70dd-401e-9fef-c20bb19ffd75.png">

**Comment by nzakas** [comment]
This is a bug. We should remove `sourcemap:true` in `rollup.config.js`. 

@tjx666 do you want to submit a pull request for this?

**Comment by tjx666** [comment]
@nzakas https://github.com/eslint/eslint-visitor-keys/pull/44
